language:      node_js
# keep the npm cache around to speed up installs
cache:
  directories:
  - "$HOME/.npm"
node_js:
- 'lts/*'
before_install:
- echo "Clone swap.core source"
- ./clone_swapcore.sh
before_script:
- echo "_________NPM install swap.react___________"
- npm install
- echo "__________NPM start swap.react____________"
- yarn start &
script:
- echo "____________LINT________________"
- npm run eslint
- echo "____________LINT________________"
- yarn test
- echo "________Build mainnet___________"
- npm run clean:mainnet && cross-env DEBUG=app:* CONFIG=mainnet.prod node ./bin/compile
- echo "________Build testnet___________"
- npm run clean:testnet && cross-env DEBUG=app:* CONFIG=testnet.prod node ./bin/compile
after_script:
- tar -cvzf build-mainnet.tgz build-mainnet/
- tar -cvzf build-testnet.tgz build-testnet/
deploy:
  provider:    releases
  api_key:
    secure:    PaxYbs26pnUamQyk5FxiEWz58dD9Z3VFpCMfw7mP52y8H0J5mIlS728dLDYag7Xah6/vwuz/EmDucM3IcNrDyzSHt7uJoqqCwXdC7xEeP8ZP7li+W8UED7UEwfJzT6d9mNlsz4TJsuDVmH2DmmO46Op/PwrxbNi6FOTtJKCMnOPZxPIimvsyA3M+PJ9y+jbs3J10I9L0fUfFxEXpjiDjf7wgIoX2VOAHLIsePV1zl8dzM3pcBYKFMTo+BDwsX5ECctUOeL73+OgkyXKuDSbnmt5QKJS4LVqjN1ptu8Sfg+pwTkcQSg9eH5UdRLOVZiqEKQtpmzZokruqck7wSJw0QEBbruWwYrb+teFbqvyd2oSB8IjIhM1On4zgLu/nYKv4iU5z7S90sUtp14Dkr2zBP6rboaHAN/Eln9NPDOgpxrewkRwGxEn3K9TwCCdKVaLyVWYVzR3vXyANdc0hNrmgXoEtMaUbzNuJZuyfXWBD6JnpgoqMzpgaIT7TTbZuzohcK8tn3NaRhoyXuq5vZiP6WMfvogO4oHhBBiH90SgjI7XtpMEjERkYgJ0uI7/qbtpZueVSIbnvx7Ye0VGMUuHazCdM4/YlIhr2R28Te80dJVpVpFW5JjHdotoH0O/SbMS0nU8ntgnrTf/Olh0rNla0KUIOIdsmY7cNG++wSGEcqX4=
  file:
  - build-mainnet.tgz
  - build-testnet.tgz
  on:
    tags:      true
